server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/airbnb
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

file.upload.path=C:/users/sushi/desktop/khushi/airbnb/properties

booking.pending.expiry=10
payment.initiated.failed=10

run.booking.expiry=false
run.inventory.generation=false